---
title: "Admissions"
output:
  pdf_document: default
  html_notebook: default
---

```{r, include=FALSE}
library(tidyverse)
library(kableExtra)
source("create_data.R")
source("calculate_thetas.R")
```

```{r, include=FALSE}
df = create_data()
original_df = as.tibble(UCBAdmissions)
original_thetas = calculate_thetas()
```

### Overall Admissions by Gender
```{r}
ggplot(original_df, aes(fill=Admit, y=n, x=Gender)) +
  geom_bar(position = "stack", stat = "identity")
```
### Overall Admissions by Department
```{r}
ggplot(original_df, aes(fill=Admit, y=n, x=Dept)) +
  geom_bar(position = "stack", stat = "identity")
```
### Admissions by Gender for Each Department
```{r}
ggplot(original_df, aes(fill=Admit, y=n, x=Gender)) +
  geom_bar(position = "stack", stat = "identity") +
  facet_wrap(vars(Dept))
```

### Admission Rates by Gender for Each Department

```{r, echo=FALSE}
```

```{r}
ggplot(original_thetas, aes(fill=Gender, y=admission_rate, x=Gender)) +
  geom_bar(position = "stack", stat = "identity") +
  facet_wrap(vars(Dept))
```
### Next
```{r}
```